version: '3'
services:
  vlad_prisma:
    container_name: vlad_prisma
    image: prismagraphql/prisma:1.29.1
    restart: always
    ports:
      - "4468:4468"
    environment:
      PRISMA_CONFIG: |
        port: 4468
        databases:
          default:
            connector: postgres
            host: vlad_db
            port: 5432
            user: prismaVlad
            password: prismaVlad
            migrations: true
  vlad_db:
    container_name: vlad_db
    image: postgres:10.6
    restart: always
    environment:
      POSTGRES_USER: prismaVlad
      POSTGRES_PASSWORD: prismaVlad
    volumes:
      - mydb:/var/lib/postgresql_vlad/data
volumes:
  mydb:
